#!/bin/bash
  
docker-compose up -d

sleep 10
  echo "Intializing replica ${rs} set"
  replicate="rs.initiate(); sleep(1000); cfg = rs.conf(); cfg.members[0].host = \"mongors1n1\"; rs.reconfig(cfg); rs.add(\"mongors1n2\"); rs.add(\"mongors1n3\"); rs.status();"
  docker exec -it mongors1n1 bash -c "echo '${replicate}' | mongo"

sleep 2
# Add better mechanisum to wait for mongos connectivity to be
# established by tailing docker log for connection readiness

#docker exec -it mongos1 bash -c "echo \"sh.addShard('mongors1/mongors1n1:27017'); sh.addShard('mongors2/mongors2n1:27017');\" | mongo "
